#line 2 "eggCfg.flex.c"

#line 4 "eggCfg.flex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cfg_create_buffer
#define yy_delete_buffer cfg_delete_buffer
#define yy_flex_debug cfg_flex_debug
#define yy_init_buffer cfg_init_buffer
#define yy_flush_buffer cfg_flush_buffer
#define yy_load_buffer_state cfg_load_buffer_state
#define yy_switch_to_buffer cfg_switch_to_buffer
#define yyin cfgin
#define yyleng cfgleng
#define yylex cfglex
#define yylineno cfglineno
#define yyout cfgout
#define yyrestart cfgrestart
#define yytext cfgtext
#define yywrap cfgwrap
#define yyalloc cfgalloc
#define yyrealloc cfgrealloc
#define yyfree cfgfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cfgrestart(cfgin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int cfgleng;

extern FILE *cfgin, *cfgout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE cfglex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-cfglineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < cfgleng; ++yyl )\
                    if ( cfgtext[yyl] == '\n' )\
                        --cfglineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cfgtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cfgtext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cfgrestart()), so that the user can continue scanning by
	 * just pointing cfgin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when cfgtext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int cfgleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow cfgwrap()'s to do buffer switches
 * instead of setting up a fresh cfgin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void cfgrestart (FILE *input_file  );
void cfg_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE cfg_create_buffer (FILE *file,int size  );
void cfg_delete_buffer (YY_BUFFER_STATE b  );
void cfg_flush_buffer (YY_BUFFER_STATE b  );
void cfgpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void cfgpop_buffer_state (void );

static void cfgensure_buffer_stack (void );
static void cfg_load_buffer_state (void );
static void cfg_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER cfg_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE cfg_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE cfg_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE cfg_scan_bytes (yyconst char *bytes,int len  );

void *cfgalloc (yy_size_t  );
void *cfgrealloc (void *,yy_size_t  );
void cfgfree (void *  );

#define yy_new_buffer cfg_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        cfgensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cfg_create_buffer(cfgin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        cfgensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cfg_create_buffer(cfgin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define cfgwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *cfgin = (FILE *) 0, *cfgout = (FILE *) 0;

typedef int yy_state_type;

extern int cfglineno;

int cfglineno = 1;

extern char *cfgtext;
#define yytext_ptr cfgtext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cfgtext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	cfgleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 99
#define YY_END_OF_BUFFER 100
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[689] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,  100,   99,
       98,   99,   11,   10,   99,   99,    2,    3,   99,    7,
       99,   99,   17,   16,   99,   14,   13,   99,   39,   99,
       99,   34,   35,   35,   99,   37,   99,   99,   99,   29,
       99,   99,   24,   25,   25,   99,   27,   99,   99,   99,
       99,   43,   99,   99,   68,   99,   99,   54,   53,   53,
       99,   55,   56,   56,   99,   99,   99,   99,   99,   99,
       56,   99,   99,   99,   99,   99,   99,   80,   99,   99,
       78,   73,   73,   74,   99,   75,   99,   92,   99,   85,

       99,   82,   99,   83,   84,   99,   99,   99,   99,   99,
       99,    0,    0,    0,    9,    3,    2,    2,    0,    0,
        0,    0,   15,   14,   14,   13,    0,   38,   35,   34,
       34,    0,   35,   35,    0,   32,    0,    0,   28,   25,
       24,   24,    0,   25,   25,    0,   20,    0,    0,    0,
       42,    0,    0,   67,   53,   54,   54,    0,   53,   57,
       53,    0,   56,    0,    0,    0,    0,    0,   50,    0,
        0,   56,    0,    0,    0,    0,    0,    0,    0,   79,
       73,   78,   78,    0,   73,   73,    0,    0,    0,    0,
       91,   82,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    2,    0,    0,    0,    0,   14,    0,
       34,    0,    0,    0,    0,    0,   24,    0,    0,    0,
        0,    0,    0,    0,   41,   54,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   78,    0,    0,    0,   70,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   33,    0,    0,    0,    0,    0,    0,   21,    0,
        0,    0,    0,   44,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   51,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   81,    0,    0,    0,    0,
        0,    0,    0,    0,   94,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   96,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   31,    0,    0,    0,    0,    0,
       19,   40,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

       71,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       95,    0,    0,    0,    0,    5,    0,   36,   36,   30,
       26,   26,    0,    0,   22,   52,   52,    0,    0,   64,
        0,    0,   59,    0,    0,    0,    0,    0,    0,    0,
        0,   60,   72,   72,    0,    0,   76,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    4,    6,
        0,   36,   26,   18,   23,   52,    0,    0,    0,   45,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   72,
        0,   77,    0,   86,    0,    0,    0,    0,    0,    0,
       97,   93,    0,    0,    0,    0,    0,    0,   45,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,   86,
        0,    0,    0,    0,    0,    8,    1,    0,    0,    0,
        0,   45,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   69,    0,   86,    0,    0,    0,    0,    0,   12,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   62,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   47,    0,    0,    0,    0,    0,    0,
        0,   88,    0,    0,    0,    0,    0,    0,   65,    0,
        0,    0,    0,   47,   47,    0,    0,    0,    0,    0,
        0,   88,   88,    0,    0,   58,   63,   61,    0,   49,
       46,   47,   47,    0,    0,   90,   87,   88,   88,    0,
        0,    0,   49,   46,    0,    0,   90,   87,    0,    0,
        0,   46,    0,    0,   87,    0,    0,    0,    0,    0,
        0,    0,    0,   48,    0,   89,   66,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    5,    1,    1,    1,    1,    1,
        1,    1,    1,    6,    7,    8,    9,   10,   10,   10,
       11,   11,   11,   11,   11,   11,   11,   12,    1,   13,
       14,   15,    1,    1,   16,   17,   18,   19,   20,   21,
       22,   23,   17,   17,   24,   25,   23,   26,   27,   17,
       17,   28,   29,   30,   31,   17,   32,   17,   33,   34,
       35,    1,   36,    1,   17,    1,   37,   38,   39,   40,

       41,   42,   43,   44,   45,   17,   46,   47,   48,   49,
       50,   51,   17,   52,   53,   54,   55,   56,   57,   58,
       59,   17,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[60] =
    {   0,
        1,    2,    3,    1,    2,    1,    1,    1,    4,    5,
        5,    1,    1,    1,    1,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    1,    1,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5
    } ;

static yyconst flex_int16_t yy_base[722] =
    {   0,
        0,    3,   15,    0,   62,   98,  132,  183,  234,    0,
       18,   27,  285,    0,  342,  387,  432,    0, 1130, 1131,
     1131,    9, 1131, 1131,    0,    0, 1120,    4,   25, 1131,
     1091, 1077, 1131, 1131,    0, 1117,    0, 1116, 1131,    0,
       25, 1115,   34,   38, 1114, 1131, 1071, 1071, 1070, 1131,
        0,   40, 1110,   44,   48, 1109, 1131, 1066, 1066, 1065,
     1064, 1131,    0, 1104, 1131,    0,   50, 1103,  107,  113,
     1102, 1131,   30,   52,   31, 1060, 1064, 1057, 1057, 1065,
       59, 1055, 1047, 1053, 1063, 1052, 1050, 1131,    0,   72,
     1090,   77,   81, 1131, 1089, 1131,   34, 1131,    0, 1131,

       84,  109, 1088, 1131, 1131, 1049, 1050, 1037, 1043, 1053,
     1042,  100, 1058, 1062,    0,  118, 1079, 1078, 1068, 1059,
     1031, 1040,    0, 1073, 1072,    0, 1064,    0,  138, 1070,
     1069,  148,  152,  156, 1048, 1131, 1024, 1036,    0,  158,
     1065, 1064,  160,  164,  168, 1043, 1131, 1028, 1018, 1030,
        0, 1040,   24,    0,  198, 1058, 1057,  170,  212, 1131,
      253,    0, 1131,   87, 1010,   41, 1025, 1016, 1131, 1019,
     1013, 1003, 1011, 1006, 1004, 1017, 1004, 1009, 1001,    0,
      188, 1043, 1042,  190,  194,  202, 1032,  129,  996, 1005,
        0,  196,    0,  992,  999,  992, 1005,  992,  997, 1010,

     1012, 1010, 1020, 1028, 1009, 1019,  993,  103, 1024, 1006,
     1022,  208,  216, 1003,  975,  982, 1018,  222,  243,  999,
      105,  971,  978,  991, 1131, 1013,  247,  257, 1006,  967,
      970,  969,  976,  975,  973,  961,  976,  964,  957,  998,
      963,  996,  949,  960,  996,  263,  267,  979, 1131,  949,
      140,  987,  948,  959,  987,  952,  985,  938,  966,  974,
      978,  968,  963,  965,  938,  947,  950,  970,  204,  977,
      966, 1131,  942,  239,  974,  963,  939,  942, 1131,  937,
      948,  259,  968, 1131,  921,  933,  919,  914,  959,  925,
      928,  923,  926, 1131,  957,  924,  955,  910,  922,  272,

      953,  929,  918,  917,  920, 1131,  902,  943,  945,  912,
      943,  898,  920,  931, 1131,   28,  928,  914,  909,  889,
      890,  918,  292,  296,  918,  887,  302,  306,  916,  883,
      884,  883,  921,  311,  318,  894,  895,  892,  881,  922,
      883,  877,  874,  879,  917,  871,  915,  873,  877,  349,
      353,  892,  871,  863,  864,  876,  907,  906,  860,  904,
      862,  891,  889, 1131,  894,  890,  873,  852,  864,  860,
      870,  298,  894,  886, 1131,  355,  892,  880,  857,  853,
     1131, 1131,  357,  888,  843,  840,  841,  842,  882,  849,
      833,  849,  834,  359,  361,  847,  833,  363,  876,  853,

     1131,  841,  837,  828,  870,  365,  367,  839,  849,  854,
     1131,  854,  854,  829,  825, 1131,  837,  369,  371, 1131,
      373,  375,  855,  822, 1131,  377,  392,  856,  813, 1131,
      814,  220, 1131,  824,  817,  822,  396,  400,  404,  408,
      816, 1131,  410,  412,  841,  813, 1131,  847,  306,  416,
      420,  436,  440,  812,  842,  841,  833,  826, 1131, 1131,
      833, 1131, 1131, 1131, 1131, 1131,  843,  807,  794,  838,
      798,  790,  797,  785,  422,  825,  430,  824,  816, 1131,
      799, 1131,  814,  813,  773,  442,  809,  444,  805,  800,
     1131, 1131,  793,  786,  772,  787,  739,  749,  777,  243,

      742,  718,  448,  452,  462,  467,  764,  754,  755,  754,
      471,  480,  484,  488,  750, 1131, 1131,  739,  454,  712,
      691,  735,  700,  681,  662,  654,  490,  680,  492,  673,
      657, 1131,  494,  653,  496,  650,  498,  635,  630, 1131,
      502,  506,  598,  586,  580,  572,  540,  539,  510,  514,
      518,  522,  566,  526,  530,  534,  538,  542,  546,  562,
      548,  547,  511,  498, 1131,  494,  488,  487,  550,  523,
      552,  519,    0,  554,  515,  556,  511,  558,  507,  277,
      562,  566,  462,  460,  456,  441,  439,  568,  571,  574,
      577,  311,  334,  582,  586,  588,  591,  594,  597,  457,

      471,  600,  453,  402,  401,  388,  388,  367,  605,  405,
      607,  401,  610,  611,  614,  401,  619,  393,  621,  383,
      624,  625,  630,  634,  345,  350,  321,  310, 1131,  636,
      639,  641,  644,  647,  648,  653,  657,  659,  662,  664,
      667,  670,  671,  674,  342, 1131, 1131, 1131,  288,    0,
      326,  677,  678,  681,  323,    0,  296,  684,  685,  688,
      691,  250,    0,  257,  694,  697,    0,  250,  703,  228,
      173,  202,  705,  191,  186,  707,  710,  133,  712,  715,
        0,  143,    0,    0,  130,    0, 1131, 1131,  726,  731,
      736,  741,  746,  751,  168,  756,  761,  766,  771,  776,

      778,  783,  788,  793,  798,  800,  805,  160,  126,  810,
      815,  820,  825,  830,  835,  117,  840,  103,  845,   68,
        3
    } ;

static yyconst flex_int16_t yy_def[722] =
    {   0,
      689,  689,  689,    3,  690,  690,  689,  689,  689,    9,
      689,  689,  689,   13,  689,  689,  689,   17,  688,  688,
      688,  688,  688,  688,  691,  688,  692,  688,  688,  688,
      688,  688,  688,  688,  693,  694,  695,  688,  688,  696,
      688,  697,  688,  688,  688,  688,  688,  688,  688,  688,
      698,  688,  699,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  700,  701,  688,  702,  688,  703,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  704,  688,
      705,  688,  688,  688,  706,  688,  688,  688,  707,  688,

      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  691,  688,  692,  692,  688,  688,
      688,  688,  693,  694,  694,  695,  688,  696,  688,  697,
      697,  688,  688,  688,  688,  688,  688,  688,  698,  688,
      699,  699,  688,  688,  688,  688,  688,  688,  688,  688,
      700,  688,  701,  702,  688,  703,  703,  688,  688,  688,
      688,  708,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  704,
      688,  705,  705,  688,  688,  688,  688,  706,  688,  688,
      707,  688,  709,  688,  688,  688,  688,  688,  688,  688,

      688,  688,  688,  692,  688,  688,  688,  688,  694,  688,
      697,  688,  688,  688,  688,  688,  699,  688,  688,  688,
      688,  688,  688,  688,  688,  703,  688,  688,  708,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  705,  688,  688,  688,  688,  688,
      688,  709,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,

      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,

      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  710,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  711,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  710,  688,

      688,  688,  688,  688,  688,  688,  688,  688,  688,  711,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  710,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  711,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  712,  688,  688,  688,  688,  688,  688,  713,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  712,  712,  688,  688,  688,  688,  688,  688,  713,

      713,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  712,  714,  688,  688,  688,  688,  688,  688,
      713,  715,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  714,  714,  688,  688,  688,  688,  688,
      688,  715,  715,  688,  688,  688,  688,  688,  688,  716,
      717,  714,  714,  688,  688,  718,  719,  715,  715,  688,
      688,  688,  716,  717,  688,  688,  718,  719,  688,  688,
      688,  717,  688,  688,  719,  688,  688,  688,  688,  688,
      720,  688,  721,  720,  688,  721,  688,    0,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,

      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688
    } ;

static yyconst flex_int16_t yy_nxt[1191] =
    {   0,
      688,   21,   21,   21,   21,   21,   21,  686,  573,  116,
      116,  593,   22,  116,  116,   22,   23,   24,   23,   25,
       62,   26,   63,   27,   28,   28,  112,   29,   30,   62,
       64,   63,  688,  119,  129,  129,  113,  114,  225,   64,
      120,  132,  364,  133,  133,  132,  365,  134,  134,  140,
      140,  143,   31,  144,  144,  143,  163,  145,  145,  155,
      155,   32,   20,   33,   34,   33,   35,   20,   20,   20,
       36,  164,  684,   20,   38,   20,   20,  165,  189,  163,
      166,  181,  181,  190,  184,  163,  185,  185,  184,  231,
      186,  186,  164,  192,  192,  232,   20,   20,   20,   33,

       34,   33,   35,   20,   20,   20,   36,  667,  172,   20,
       38,   20,   20,  173,  158,  163,  159,  159,  192,  192,
      158,  663,  161,  161,  200,  160,  201,  116,  116,  160,
      252,  160,   20,   20,   39,  160,   40,  688,   41,  163,
       42,   43,   44,  249,   45,   46,  160,  129,  129,  266,
      160,  277,  160,  267,  160,  278,  160,  212,  213,  132,
      160,  134,  134,  132,  229,  129,  129,  140,  140,  218,
      219,  143,  126,  145,  145,  143,   47,  140,  140,  227,
      228,  687,   48,  685,   49,   39,  304,   40,  682,   41,
      305,   42,   43,   44,  675,   45,   46,  181,  181,  246,

      247,  184,  673,  186,  186,  192,  192,  155,  155,  184,
      672,  181,  181,  323,  324,  269,  160,  213,  213,  158,
      160,  161,  161,  269,  678,  270,  270,   47,  470,  274,
      160,  219,  219,   48,  160,   49,   50,  160,   51,  669,
       52,  160,   53,   54,   55,  160,   56,   57,  327,  328,
      274,  160,  275,  275,  282,  160,  228,  228,  675,  160,
      158,  471,  155,  155,  282,  672,  283,  283,  334,  335,
      300,  160,  247,  247,  300,  160,  301,  301,   58,  523,
       59,  350,  351,  524,   60,  580,   61,   65,  601,   66,
      671,   67,  160,   68,   69,   70,  160,   71,   72,  372,

      160,  324,  324,  372,  657,  373,  373,  418,  419,  376,
       73,  328,  328,  376,  484,  377,  377,   74,  383,  613,
      335,  335,  593,   75,   76,  383,   77,  384,  384,   78,
      654,   79,   80,   81,  651,   82,   83,   84,   85,   86,
      662,   87,  614,   74,   88,  593,   89,  485,   90,  644,
       91,   92,   93,   94,   95,   96,  398,  649,  351,  351,
      398,  648,  399,  399,  421,  422,  426,  427,  437,  438,
      439,  440,  443,  444,  450,  451,  452,  453,  419,  419,
      462,  462,  422,  422,  463,  463,  427,  427,   97,   88,
      647,   89,  646,   90,  619,   91,   92,   93,   94,   95,

       96,  466,  466,  475,  617,  438,  438,  475,  615,  476,
      476,  477,  611,  440,  440,  477,  609,  478,  478,  444,
      444,  480,  480,  486,  629,  451,  451,  486,  628,  487,
      487,  503,  504,   97,   98,  627,   99,  100,  101,  505,
      506,  102,  102,  488,  103,  453,  453,  488,  626,  489,
      489,  511,  512,  513,  514,  527,  625,  504,  504,  527,
      602,  528,  528,  541,  542,  621,  104,  105,  601,  529,
      106,  506,  506,  107,  529,  608,  530,  530,  535,  622,
      512,  512,  601,  108,  109,  110,  111,  535,  607,  536,
      536,  537,  606,  514,  514,  537,  605,  538,  538,  549,

      550,  551,  552,  554,  555,  556,  557,  558,  559,  561,
      604,  542,  542,  561,  578,  562,  562,  569,  576,  550,
      550,  569,  574,  570,  570,  571,  571,  552,  552,  571,
      569,  572,  572,  574,  587,  555,  555,  574,  586,  575,
      575,  576,  585,  557,  557,  576,  584,  577,  577,  578,
      583,  559,  559,  578,  561,  579,  579,  581,  582,  588,
      589,  590,  591,  594,  595,  596,  597,  598,  599,  602,
      580,  582,  582,  602,  573,  603,  603,  589,  589,  609,
      610,  610,  609,  591,  591,  611,  612,  612,  611,  615,
      568,  595,  595,  615,  567,  616,  616,  597,  597,  617,

      618,  618,  617,  599,  599,  619,  620,  620,  619,  623,
      624,  630,  566,  632,  631,  631,  633,  633,  613,  614,
      565,  593,  635,  636,  637,  638,  564,  640,  639,  639,
      641,  641,  621,  622,  563,  601,  643,  644,  560,  624,
      624,  644,  537,  645,  645,  631,  631,  650,  631,  631,
      633,  633,  651,  633,  633,  652,  653,  535,  635,  635,
      654,  534,  637,  637,  654,  553,  655,  655,  639,  639,
      656,  639,  639,  641,  641,  657,  641,  641,  658,  659,
      529,  643,  643,  660,  661,  652,  653,  527,  635,  635,
      665,  666,  658,  659,  548,  643,  643,  661,  661,  669,

      670,  670,  669,  666,  666,  673,  674,  674,  673,  676,
      547,  679,  677,  677,  680,  680,  677,  677,  681,  677,
      677,  680,  680,  683,  680,  680,   20,   20,   20,   20,
       20,   37,   37,   37,   37,   37,  115,  115,  546,  115,
      115,  117,  545,  522,  117,  117,  123,  123,  544,  123,
      123,  124,  543,  540,  124,  124,  128,  128,  539,  128,
      128,  130,  534,  533,  130,  130,  139,  139,  532,  139,
      139,  141,  531,  526,  141,  141,  151,  151,  525,  151,
      151,  153,  153,  154,  154,  522,  154,  154,  156,  521,
      520,  156,  156,  180,  180,  519,  180,  180,  182,  518,

      517,  182,  182,  188,  188,  191,  191,  516,  191,  191,
      499,  515,  488,  499,  499,  510,  486,  195,  510,  510,
      592,  484,  509,  592,  592,  600,  508,  507,  600,  600,
      634,  477,  475,  634,  634,  642,  502,  501,  642,  642,
      664,  500,  168,  664,  664,  668,  470,  498,  668,  668,
      497,  496,  495,  494,  493,  492,  491,  490,  483,  482,
      481,  479,  474,  473,  472,  469,  468,  467,  465,  464,
      461,  460,  459,  458,  457,  456,  455,  454,  449,  448,
      447,  446,  445,  398,  442,  441,  436,  435,  434,  433,
      432,  431,  430,  429,  428,  383,  425,  424,  423,  376,

      420,  372,  417,  416,  415,  414,  413,  412,  411,  410,
      409,  408,  407,  257,  406,  405,  404,  403,  402,  401,
      400,  397,  396,  395,  242,  394,  393,  392,  391,  390,
      389,  388,  387,  386,  385,  382,  381,  380,  379,  378,
      375,  374,  371,  370,  369,  368,  367,  366,  363,  362,
      361,  360,  359,  358,  357,  356,  355,  354,  353,  352,
      300,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      340,  339,  338,  337,  336,  282,  333,  332,  331,  330,
      329,  274,  326,  325,  269,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  309,  308,

      307,  306,  303,  302,  245,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  226,  281,  280,  279,  276,  217,  273,  272,  271,
      211,  268,  209,  265,  264,  263,  204,  262,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  251,  250,  248,
      183,  245,  244,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  230,  157,  226,  224,  223,  222,
      221,  220,  142,  217,  216,  215,  214,  131,  211,  210,
      125,  209,  208,  207,  206,  205,  118,  204,  203,  202,
      199,  198,  197,  196,  195,  194,  193,  187,  183,  179,

      178,  177,  176,  175,  174,  171,  170,  169,  168,  167,
      162,  157,  152,  150,  149,  148,  147,  146,  142,  138,
      137,  136,  135,  131,  127,  125,  122,  121,  118,  688,
       19,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688
    } ;

static yyconst flex_int16_t yy_chk[1191] =
    {   0,
        0,    1,    1,    1,    2,    2,    2,  721,  573,   26,
       26,  573,    1,   28,   28,    2,    3,    3,    3,    3,
       11,    3,   11,    3,    3,    3,   22,    3,    3,   12,
       11,   12,  153,   29,   41,   41,   22,   22,  153,   12,
       29,   43,  316,   43,   43,   44,  316,   44,   44,   52,
       52,   54,    3,   54,   54,   55,   73,   55,   55,   67,
       67,    3,    5,    5,    5,    5,    5,    5,    5,    5,
        5,   74,  720,    5,    5,    5,    5,   75,   97,   73,
       75,   90,   90,   97,   92,   81,   92,   92,   93,  166,
       93,   93,   74,  101,  101,  166,    5,    5,    6,    6,

        6,    6,    6,    6,    6,    6,    6,  718,   81,    6,
        6,    6,    6,   81,   69,  164,   69,   69,  102,  102,
       70,  716,   70,   70,  112,   69,  112,  116,  116,   69,
      709,   70,    6,    6,    7,   70,    7,  188,    7,  164,
        7,    7,    7,  188,    7,    7,   69,  129,  129,  208,
       69,  221,   70,  208,   69,  221,   70,  132,  132,  133,
       70,  133,  133,  134,  708,  134,  134,  140,  140,  143,
      143,  144,  695,  144,  144,  145,    7,  145,  145,  158,
      158,  685,    7,  682,    7,    8,  251,    8,  678,    8,
      251,    8,    8,    8,  675,    8,    8,  181,  181,  184,

      184,  185,  674,  185,  185,  192,  192,  155,  155,  186,
      672,  186,  186,  269,  269,  212,  155,  212,  212,  159,
      155,  159,  159,  213,  671,  213,  213,    8,  432,  218,
      159,  218,  218,    8,  159,    8,    9,  155,    9,  670,
        9,  155,    9,    9,    9,  155,    9,    9,  274,  274,
      219,  159,  219,  219,  227,  159,  227,  227,  668,  159,
      161,  432,  161,  161,  228,  664,  228,  228,  282,  282,
      246,  161,  246,  246,  247,  161,  247,  247,    9,  500,
        9,  300,  300,  500,    9,  580,    9,   13,  580,   13,
      662,   13,  161,   13,   13,   13,  161,   13,   13,  323,

      161,  323,  323,  324,  657,  324,  324,  372,  372,  327,
       13,  327,  327,  328,  449,  328,  328,   13,  334,  592,
      334,  334,  592,   13,   13,  335,   13,  335,  335,   13,
      655,   13,   13,   13,  651,   13,   13,   13,   13,   13,
      649,   13,  593,   13,   15,  593,   15,  449,   15,  645,
       15,   15,   15,   15,   15,   15,  350,  628,  350,  350,
      351,  627,  351,  351,  376,  376,  383,  383,  394,  394,
      395,  395,  398,  398,  406,  406,  407,  407,  418,  418,
      419,  419,  421,  421,  422,  422,  426,  426,   15,   16,
      626,   16,  625,   16,  620,   16,   16,   16,   16,   16,

       16,  427,  427,  437,  618,  437,  437,  438,  616,  438,
      438,  439,  612,  439,  439,  440,  610,  440,  440,  443,
      443,  444,  444,  450,  608,  450,  450,  451,  607,  451,
      451,  475,  475,   16,   17,  606,   17,   17,   17,  477,
      477,   17,   17,  452,   17,  452,  452,  453,  605,  453,
      453,  486,  486,  488,  488,  503,  604,  503,  503,  504,
      603,  504,  504,  519,  519,  600,   17,   17,  600,  505,
       17,  505,  505,   17,  506,  587,  506,  506,  511,  601,
      511,  511,  601,   17,   17,   17,   17,  512,  586,  512,
      512,  513,  585,  513,  513,  514,  584,  514,  514,  527,

      527,  529,  529,  533,  533,  535,  535,  537,  537,  541,
      583,  541,  541,  542,  579,  542,  542,  549,  577,  549,
      549,  550,  575,  550,  550,  551,  572,  551,  551,  552,
      570,  552,  552,  554,  568,  554,  554,  555,  567,  555,
      555,  556,  566,  556,  556,  557,  564,  557,  557,  558,
      563,  558,  558,  559,  562,  559,  559,  561,  561,  569,
      569,  571,  571,  574,  574,  576,  576,  578,  578,  581,
      560,  581,  581,  582,  553,  582,  582,  588,  588,  588,
      589,  589,  589,  590,  590,  590,  591,  591,  591,  594,
      548,  594,  594,  595,  547,  595,  595,  596,  596,  596,

      597,  597,  597,  598,  598,  598,  599,  599,  599,  602,
      602,  609,  546,  611,  609,  609,  611,  611,  613,  614,
      545,  613,  614,  615,  615,  617,  544,  619,  617,  617,
      619,  619,  621,  622,  543,  621,  622,  623,  539,  623,
      623,  624,  538,  624,  624,  630,  630,  631,  631,  631,
      632,  632,  633,  633,  633,  634,  635,  536,  634,  635,
      636,  534,  636,  636,  637,  531,  637,  637,  638,  638,
      639,  639,  639,  640,  640,  641,  641,  641,  642,  643,
      530,  642,  643,  644,  644,  652,  653,  528,  652,  653,
      654,  654,  658,  659,  526,  658,  659,  660,  660,  660,

      661,  661,  661,  665,  665,  665,  666,  666,  666,  669,
      525,  673,  669,  669,  673,  673,  676,  676,  677,  677,
      677,  679,  679,  680,  680,  680,  689,  689,  689,  689,
      689,  690,  690,  690,  690,  690,  691,  691,  524,  691,
      691,  692,  523,  522,  692,  692,  693,  693,  521,  693,
      693,  694,  520,  518,  694,  694,  696,  696,  515,  696,
      696,  697,  510,  509,  697,  697,  698,  698,  508,  698,
      698,  699,  507,  502,  699,  699,  700,  700,  501,  700,
      700,  701,  701,  702,  702,  499,  702,  702,  703,  498,
      497,  703,  703,  704,  704,  496,  704,  704,  705,  495,

      494,  705,  705,  706,  706,  707,  707,  493,  707,  707,
      710,  490,  489,  710,  710,  711,  487,  485,  711,  711,
      712,  484,  483,  712,  712,  713,  481,  479,  713,  713,
      714,  478,  476,  714,  714,  715,  474,  473,  715,  715,
      717,  472,  471,  717,  717,  719,  470,  469,  719,  719,
      468,  467,  461,  458,  457,  456,  455,  454,  448,  446,
      445,  441,  436,  435,  434,  431,  429,  428,  424,  423,
      417,  415,  414,  413,  412,  410,  409,  408,  405,  404,
      403,  402,  400,  399,  397,  396,  393,  392,  391,  390,
      389,  388,  387,  386,  385,  384,  380,  379,  378,  377,

      374,  373,  371,  370,  369,  368,  367,  366,  365,  363,
      362,  361,  360,  359,  358,  357,  356,  355,  354,  353,
      352,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      340,  339,  338,  337,  336,  333,  332,  331,  330,  329,
      326,  325,  322,  321,  320,  319,  318,  317,  314,  313,
      312,  311,  310,  309,  308,  307,  305,  304,  303,  302,
      301,  299,  298,  297,  296,  295,  293,  292,  291,  290,
      289,  288,  287,  286,  285,  283,  281,  280,  278,  277,
      276,  275,  273,  271,  270,  268,  267,  266,  265,  264,
      263,  262,  261,  260,  259,  258,  257,  256,  255,  254,

      253,  252,  250,  248,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      229,  226,  224,  223,  222,  220,  217,  216,  215,  214,
      211,  210,  209,  207,  206,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  196,  195,  194,  190,  189,  187,
      183,  182,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  168,  167,  165,  157,  156,  152,  150,  149,
      148,  146,  142,  141,  138,  137,  135,  131,  130,  127,
      125,  124,  122,  121,  120,  119,  118,  117,  114,  113,
      111,  110,  109,  108,  107,  106,  103,   95,   91,   87,

       86,   85,   84,   83,   82,   80,   79,   78,   77,   76,
       71,   68,   64,   61,   60,   59,   58,   56,   53,   49,
       48,   47,   45,   42,   38,   36,   32,   31,   27,   19,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688,
      688,  688,  688,  688,  688,  688,  688,  688,  688,  688
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[100] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int cfg_flex_debug;
int cfg_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cfgtext;
#line 1 "eggCfg.flex"
#line 4 "eggCfg.flex"
#define _GNU_SOURCE
     
#include <stdio.h>
#include <stdlib.h>
#include "eggCfg.bison.h"

int parmnum = 0;
int fileeof=1;
int fileline=0;

#undef YY_INPUT


#define YY_INPUT(buf, retval, maxlen)           \
    {                                           \
    while(1)                                    \
    {                                           \
        char* ret = fgets(buf, maxlen, cfgin);   \
        fileline++;                             \
        if(ret)                                 \
        {                                       \
            if (buf[0] == '\n')                 \
                continue;                       \
            retval=strlen(buf);                 \
        }                                       \
        else                                    \
        {                                       \
            retval = 0;                         \
            fileeof = 0;                        \
        }                                       \
        break;                                  \
    }                                           \
}


#line 1035 "eggCfg.flex.c"

#define INITIAL 0
#define CORE 1
#define ANA 2
#define SOCK 3
#define SOCKD 4
#define RWS 5
#define RWSUNIT 6
#define CLUSTER 7
#define CTUNIT 8

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cfglex_destroy (void );

int cfgget_debug (void );

void cfgset_debug (int debug_flag  );

YY_EXTRA_TYPE cfgget_extra (void );

void cfgset_extra (YY_EXTRA_TYPE user_defined  );

FILE *cfgget_in (void );

void cfgset_in  (FILE * in_str  );

FILE *cfgget_out (void );

void cfgset_out  (FILE * out_str  );

int cfgget_leng (void );

char *cfgget_text (void );

int cfgget_lineno (void );

void cfgset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cfgwrap (void );
#else
extern int cfgwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( cfgtext, cfgleng, 1, cfgout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( cfgin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( cfgin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, cfgin))==0 && ferror(cfgin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(cfgin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cfglex (void);

#define YY_DECL int cfglex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cfgtext and cfgleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 62 "eggCfg.flex"

#line 1232 "eggCfg.flex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! cfgin )
			cfgin = stdin;

		if ( ! cfgout )
			cfgout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			cfgensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				cfg_create_buffer(cfgin,YY_BUF_SIZE );
		}

		cfg_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of cfgtext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 689 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1131 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < cfgleng; ++yyl )
				if ( cfgtext[yyl] == '\n' )
					   
    cfglineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN ANA;return START;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return PATH;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return NUMBER;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 67 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return BASEPATH_CORE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 68 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return LOGPATH_CORE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 69 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return LOGLEVEL_CORE;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 70 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return cfgtext[0];}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 71 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN INITIAL;return END;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 73 "eggCfg.flex"
{return NOTE;}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 74 "eggCfg.flex"
{return 0;};
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 75 "eggCfg.flex"
;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 76 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN CORE;return END;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 77 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return DLLNAME;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 78 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext);  return PATH;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 79 "eggCfg.flex"
{return NOTE;}
	YY_BREAK
case 16:
/* rule 16 can match eol */
YY_RULE_SETUP
#line 80 "eggCfg.flex"
{return 0;};
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 81 "eggCfg.flex"
;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 83 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN INITIAL; return END;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 84 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return FSOCK_D;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 85 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return FIP_D;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 86 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return FPORT_D;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 87 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return LOGPATH_D;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 88 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return LOGLEVEL_D;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 90 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return PATH;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 91 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return NUMBER;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 92 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return IP;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 93 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return cfgtext[0];}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 94 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return NOTE;}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 95 "eggCfg.flex"
{return 0;};
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 98 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN INITIAL;return END;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 99 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return FSOCK;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 100 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return FIP;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 101 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return FPORT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 102 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return PATH;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 103 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return NUMBER;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 104 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return IP;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 105 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return cfgtext[0];}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 106 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return NOTE;}
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 107 "eggCfg.flex"
{return 0;};
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 110 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN INITIAL;return END;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 111 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN RWSUNIT;return NAME_R;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 112 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return NOTE;}
	YY_BREAK
case 43:
/* rule 43 can match eol */
YY_RULE_SETUP
#line 113 "eggCfg.flex"
{return 0;};
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 115 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN RWS;return END;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 116 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return EGGPATH;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 117 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return EGGPATH;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 118 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return EGGPATH;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 119 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return EGGPATH;} 
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 120 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return EGGPATH;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 123 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return FIP_R;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 124 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return FPORT_R;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 125 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return IP;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 126 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return NUMBER;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 127 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return PATH;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 128 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return cfgtext[0];}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 129 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return BOOL;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 130 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return TIME;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 133 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return CONNECT_R;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 134 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return LOGFILE_R;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 135 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return WORKDIR_R;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 136 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return MEMEXE_R;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 137 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return SYNCFREQ_R;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 138 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return EXPORTEXE_R;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 139 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return COUNTER_R;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 140 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return MSERVERMAX_R;}  
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 141 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return NOWAIT_R;}  
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 143 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return NOTE;}
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 144 "eggCfg.flex"
{return 0;};
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 148 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN INITIAL;return END;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 149 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN CTUNIT;return NAME_C;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 152 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return FLISTEN_C;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 153 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return IP;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 154 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return NUMBER;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 155 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return cfgtext[0];}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 156 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return cfgtext[0];}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 157 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return LOGPATH_C;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 158 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return LOGLEVEL_C;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 160 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return PATH;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 164 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return NOTE;}
	YY_BREAK
case 80:
/* rule 80 can match eol */
YY_RULE_SETUP
#line 165 "eggCfg.flex"
{return 0;};
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 168 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN CLUSTER;return END;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 170 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return NUMBER;} 
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 171 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return cfgtext[0];}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 172 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return cfgtext[0];}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 173 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return cfgtext[0];}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 176 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return EGGPATH;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 177 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return EGGPATH;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 178 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return EGGPATH;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 179 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return EGGPATH;} 
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 180 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return EGGPATH;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 182 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); return NOTE;}
	YY_BREAK
case 92:
/* rule 92 can match eol */
YY_RULE_SETUP
#line 183 "eggCfg.flex"
{return 0;};
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 186 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN CORE;return START;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 187 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN RWS;return START;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 188 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN SOCKD;return START;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 189 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN SOCK;return START;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 190 "eggCfg.flex"
{strcpy(cfglval.str, cfgtext); BEGIN CLUSTER;return START;}
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 191 "eggCfg.flex"
{return 0;};
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 192 "eggCfg.flex"
ECHO;
	YY_BREAK
#line 1829 "eggCfg.flex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CORE):
case YY_STATE_EOF(ANA):
case YY_STATE_EOF(SOCK):
case YY_STATE_EOF(SOCKD):
case YY_STATE_EOF(RWS):
case YY_STATE_EOF(RWSUNIT):
case YY_STATE_EOF(CLUSTER):
case YY_STATE_EOF(CTUNIT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed cfgin at a new source and called
			 * cfglex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = cfgin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( cfgwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cfgtext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cfglex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cfgrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cfgrestart(cfgin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cfgrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 689 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 689 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 688);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up cfgtext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --cfglineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cfgrestart(cfgin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cfgwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cfgtext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    cfglineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cfgrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        cfgensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            cfg_create_buffer(cfgin,YY_BUF_SIZE );
	}

	cfg_init_buffer(YY_CURRENT_BUFFER,input_file );
	cfg_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void cfg_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cfgpop_buffer_state();
	 *		cfgpush_buffer_state(new_buffer);
     */
	cfgensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cfg_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (cfgwrap()) processing, but the only time this flag
	 * is looked at is after cfgwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void cfg_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	cfgin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cfg_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cfgalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cfg_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cfgalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cfg_create_buffer()" );

	b->yy_is_our_buffer = 1;

	cfg_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cfg_create_buffer()
 * 
 */
    void cfg_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cfgfree((void *) b->yy_ch_buf  );

	cfgfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cfgrestart() or at EOF.
 */
    static void cfg_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	cfg_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cfg_init_buffer was _probably_
     * called from cfgrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void cfg_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cfg_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void cfgpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	cfgensure_buffer_stack();

	/* This block is copied from cfg_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cfg_switch_to_buffer. */
	cfg_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void cfgpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	cfg_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		cfg_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cfgensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)cfgalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cfgensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)cfgrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cfgensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cfg_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cfgalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cfg_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cfg_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cfglex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cfg_scan_bytes() instead.
 */
YY_BUFFER_STATE cfg_scan_string (yyconst char * yystr )
{
    
	return cfg_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to cfglex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cfg_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cfgalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cfg_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cfg_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cfg_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cfgtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cfgtext[cfgleng] = (yy_hold_char); \
		(yy_c_buf_p) = cfgtext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		cfgleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int cfgget_lineno  (void)
{
        
    return cfglineno;
}

/** Get the input stream.
 * 
 */
FILE *cfgget_in  (void)
{
        return cfgin;
}

/** Get the output stream.
 * 
 */
FILE *cfgget_out  (void)
{
        return cfgout;
}

/** Get the length of the current token.
 * 
 */
int cfgget_leng  (void)
{
        return cfgleng;
}

/** Get the current token.
 * 
 */

char *cfgget_text  (void)
{
        return cfgtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void cfgset_lineno (int  line_number )
{
    
    cfglineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see cfg_switch_to_buffer
 */
void cfgset_in (FILE *  in_str )
{
        cfgin = in_str ;
}

void cfgset_out (FILE *  out_str )
{
        cfgout = out_str ;
}

int cfgget_debug  (void)
{
        return cfg_flex_debug;
}

void cfgset_debug (int  bdebug )
{
        cfg_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cfglex_destroy(), so don't allocate here.
     */

    /* We do not touch cfglineno unless the option is enabled. */
    cfglineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    cfgin = stdin;
    cfgout = stdout;
#else
    cfgin = (FILE *) 0;
    cfgout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cfglex_init()
     */
    return 0;
}

/* cfglex_destroy is for both reentrant and non-reentrant scanners. */
int cfglex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cfg_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cfgpop_buffer_state();
	}

	/* Destroy the stack itself. */
	cfgfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cfglex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cfgalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *cfgrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cfgfree (void * ptr )
{
	free( (char *) ptr );	/* see cfgrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 192 "eggCfg.flex"





